### ISSUE TITLE
Roadmap? Help wanted?

### ISSUE THREAD

**Issue by romeovs** [jingweno/godzilla#16]
This looks like a cool project!
Is there a roadmap of things that need to happen and in what order? Are there areas you'd like help in? A TODO list would be nice to help new developers take up this project.

Ideally, in the future, I could use this to compile and include my React server side renderer into my go binary so I don't need to run a separate server for SSR.

**Comment by lobesoftllc** [comment]
seems like a dead project...

**Comment by zaydek-old** [comment]
DON'T SAY THAT @CristianPietrobon

**Comment by romeovs** [comment]
Really seems dead... Closing
