### ISSUE TITLE
Add a meaningful benchmark

### ISSUE THREAD

**Issue by DirtyHairy** [jingweno/godzilla#2]
For the sake of fairness, you should include a benchmark of nontrivial real-world code that consists of more than one statement in your documentation. As it stands, you are comparing of what I presume is a single call to your runtime to the bootstrap of a complex JIT... seriously :smiling_imp: ?

**Comment by jingweno** [comment]
For the sake of fairness, this project is just getting started and only very limited language features are implemented. So the `console.log` is the only thing that is benchmarkable. I have already [stated clear in the README](https://github.com/jingweno/godzilla#performance). Please contribute if you want to see more meaningful benchmark :)

**Comment by DirtyHairy** [comment]
If current functionality is that limited, I would suggest removing the benchmark alltogether and wait until there is actually something to benchmark. The way it stands, the benchmark is meaningless at best and potentially misleading :smirk:

**Comment by jingweno** [comment]
Why removing? I don't think it's really "meaningless". The benchmark is about program startup time and it's meaningful to a lot of programs. And it also proves the approach Godzilla takes is beating Node in one way currently. I made it explicit though in the README: https://github.com/jingweno/godzilla/pull/6.
